apiVersion: v1
kind: Pod
metadata:
  name: saleor-platform-jaeger-1
  labels:
    app: jaeger
spec:
  containers:
  - name: jaeger
    image: jaegertracing/all-in-one
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5775
        protocol: UDP
        name: port-1
      - containerPort: 6831
        protocol: UDP
        name: port-2
      - containerPort: 6832
        protocol: UDP
        name: port-3
      - containerPort: 5778
        name: port-4
      - containerPort: 16686
        name: port-5
      - containerPort: 14268
        name: port-6
      - containerPort: 9411
        name: port-7
      

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - port: 5775
    targetPort: 5775
    name: port-1
  - port: 6831
    targetPort: 6831
    name: port-2
  - port: 6832
    targetPort: 6832
    name: port-3
  - port: 5778
    targetPort: 5778
    name: port-4
  - port: 16686
    targetPort: 16686
    name: port-5
  - port: 14268
    targetPort: 14268
    name: port-6
  - port: 9411
    targetPort: 9411
    name: port-7