apiVersion: v1
kind: Pod
metadata:
  name: saleor-platform-mailhog-1
  labels:
    app: mail-hog
spec:
  containers:
  - name: mail-hog
    image: mailhog/mailhog
    ports:
      - containerPort: 1025
      - containerPort: 8025


---
apiVersion: v1
kind: Service
metadata:
  name: mail-hog
spec:
  selector:
    app: mail-hog
  ports:
  - port: 1025
    targetPort: 1025
    name: port-1
  - port: 8025
    targetPort: 8025
    name: port-2