apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: saleor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: saleor
    spec:
      containers:
        - name: saleor
          image: praveenrajnikanth/workshop:saleor
          ports:
            - containerPort: 8000
          env:
            - name: ALLOWED_HOSTS
              value: "localhost,api,0.0.0.0"
            - name: STOREFRONT_URL
              value: "http://localhost:3000/"
            - name: AEGER_AGENT_HOST
              value: "jaeger"
            - name: DASHBOARD_URL
              value: "http://localhost:9000/"
            - name: DATABASE_URL
              value: "postgres://saleor:saleor@db/saleor"
            - name: DEFAULT_FROM_EMAIL
              value: "noreply@example.com"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/1"
            - name: SECRET_KEY
              value: "changeme"
            - name: DEFAULT_CHANNEL_SLUG
              value: "default-channel"
      imagePullSecrets:
        - name: regcred


---
apiVersion: v1
kind: Service
metadata:
  name: saleor
spec:
  type: LoadBalancer
  selector:
    app: saleor
  ports:
  - port: 80
    targetPort: 8000