---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-server
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: saleor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: saleor
      labels:
        app: saleor
    spec:
      containers:
        - name: saleor
          image: praveenrajnikanth/workshop:saleor
          ports:
            - containerPort: 8000
              protocol: TCP
          command:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          env:
            - name: ALLOWED_HOSTS
              value: "localhost,api,0.0.0.0"
            - name: STOREFRONT_URL
              value: "http://localhost:3000/"
            - name: AEGER_AGENT_HOST
              value: "jaeger"
            - name: DASHBOARD_URL
              value: "http://localhost:9000/"
            - name: SECRET_KEY
              value: "changeme"
      imagePullSecrets:
        - name: regcred


---
apiVersion: v1
kind: Service
metadata:
  name: saleor-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: saleor
  ports:
    - name: saleorport
      port: 80
      targetPort: 8000