apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-platform-worker-1
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: saleor-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: saleor-worker
    spec:
      containers:
        - name: saleor
          image: praveenrajnikanth/workshop:saleor
          env:
            - name: ALLOWED_HOSTS
              value: "localhost,api,0.0.0.0"
            - name: STOREFRONT_URL
              value: "http://localhost:3000/"
            - name: AEGER_AGENT_HOST
              value: "jaeger"
            - name: DASHBOARD_URL
              value: "http://localhost:9000/"
            - name: DATABASE_URL
              value: "postgres://saleor:saleor@db/saleor"
            - name: DEFAULT_FROM_EMAIL
              value: "noreply@example.com"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/1"
            - name: SECRET_KEY
              value: "changeme"
            - name: DEFAULT_CHANNEL_SLUG
              value: "default-channel"
          volumeMounts:
            - name: saleor
              mountPath: /app/media
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-media
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce





---
apiVersion: v1
kind: Service
metadata:
  name: saleor-worker
spec:
  selector:
    app: saleor-worker
  ports:
  - port: 80
    targetPort: 8000